### ISSUE TITLE
Show Both Commands when you right click on Editor

### ISSUE THREAD

**Issue by tekdj7** [brokensandals/paste-relative-path#3]
Instead of always having to go to Command Palette, and/or creating keyboard shortcuts, show the 2 commands when you right click in the editor, and/or give us the option to enable/disable this.

**Comment by brokensandals** [comment]
I didn't realize extensions could even do this, but it looks like maybe an `editor/context` on [this extension point](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) would do it. I'll have to look into whether there's a way to control it via a preference.

**Comment by tekdj7** [comment]
Yes. Several extensions I've installed show commands as options when I right click the file. Maybe take a look at some extensions dealing with files for ideas. When I get a sec will see if I can send you some extensions that do it so you can reference.

**Comment by brokensandals** [comment]
This took me so long you may no longer care, but, it's available in version 1.4.0. (And it turns out, yes, you can make it conditional on config, by putting `config.nameOfConfig` in the `"when"` section.)
