### ISSUE TITLE
preference order (filename, title)

### ISSUE THREAD

**Issue by tekdj7** [brokensandals/paste-relative-path#4]
A setting should be added that we can enable whether to use filename for link, or title for link.  And is you stated, if title isn't feasible, then it falls back to filename.

**Comment by brokensandals** [comment]
Are you saying that for the `Paste Relative Path as Markdown Link` command, you want a way to disable it from even attempting to use the title?

**Comment by tekdj7** [comment]
Yes. We should have the option, as in some cases we may want the filename and not the title, for instance. So it should be a preference setting, with options:
- Filename
- Title (and if not feasible, it falls back to filename)

**Comment by brokensandals** [comment]
That's reasonable, I'll make the change when I get a chance.

**Comment by brokensandals** [comment]
Released in 1.3.0. Search for "Paste Relative Path: Use Title For Markdown Links" in settings and uncheck the box.

**Comment by tekdj7** [comment]
Thanks, looks good.
